### ISSUE TITLE
ValueError raised when attribute has type `h5py.Reference`

### ISSUE THREAD

**Issue by fsvenson** [h5netcdf/h5netcdf#203]
#### What happened:

I have a NetCDF4 file where I make use of [HDF5 Image Specification](https://docs.hdfgroup.org/hdf5/develop/_i_m_g.html) metadata. When a color palette is used for an image an attribute with a reference to the actual color palette data is used. When such an attribute is read by `h5netcdf` the error is raised from [this line](https://github.com/h5netcdf/h5netcdf/blob/main/h5netcdf/attrs.py#L72).

#### What you expected to happen:

I expect such attributes to be possible to read.

#### MCVE Code Sample
I don't have a minimal example at hand, but I could provide one if necessary. However, it is quite clear that the issue is in the `attrs.py` module in the `__getitem__` function. I reckon a reasonable fix would be to make a check similar to what is done for empty attributes, and return the attribute as is if it's a reference.

#### Anything else we need to know?:
 \-

#### Version

<details><summary>Output of <tt>print(h5py.version.info, f"\nh5netcdf {h5netcdf.__version__}")</tt></summary>

Summary of the h5py configuration
---------------------------------

h5py    3.7.0
HDF5    1.10.7
Python  3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.23.5
cython (built with) 0.29.32
numpy (built against) 1.21.6
HDF5 (built against) 1.10.7

h5netcdf 1.1.0

</details>

**Comment by kmuehlbauer** [comment]
@fsvenson Thanks for raising this. Could you share the full error traceback please?

**Comment by fsvenson** [comment]
It happened when reading via `xarray`:
```
Traceback (most recent call last):
  File "/home/efes/dev/issues/DATA-375-3d-vis/test.py", line 38, in <module>
    bm = xr.open_dataset(
  File "/home/efes/.cache/pypoetry/virtualenvs/meta-world-v48m9Vhg-py3.10/lib/python3.10/site-packages/xarray/backends/api.py", line 540, in open_dataset
    backend_ds = backend.open_dataset(
  File "/home/efes/.cache/pypoetry/virtualenvs/meta-world-v48m9Vhg-py3.10/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 419, in open_dataset
    ds = store_entrypoint.open_dataset(
  File "/home/efes/.cache/pypoetry/virtualenvs/meta-world-v48m9Vhg-py3.10/lib/python3.10/site-packages/xarray/backends/store.py", line 28, in open_dataset
    vars, attrs = store.load()
  File "/home/efes/.cache/pypoetry/virtualenvs/meta-world-v48m9Vhg-py3.10/lib/python3.10/site-packages/xarray/backends/common.py", line 128, in load
    (_decode_variable_name(k), v) for k, v in self.get_variables().items()
  File "/home/efes/.cache/pypoetry/virtualenvs/meta-world-v48m9Vhg-py3.10/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 221, in get_variables
    return FrozenDict(
  File "/home/efes/.cache/pypoetry/virtualenvs/meta-world-v48m9Vhg-py3.10/lib/python3.10/site-packages/xarray/core/utils.py", line 469, in FrozenDict
    return Frozen(dict(*args, **kwargs))
  File "/home/efes/.cache/pypoetry/virtualenvs/meta-world-v48m9Vhg-py3.10/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 222, in <genexpr>
    (k, self.open_store_variable(k, v)) for k, v in self.ds.variables.items()
  File "/home/efes/.cache/pypoetry/virtualenvs/meta-world-v48m9Vhg-py3.10/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 188, in open_store_variable
    attrs = _read_attributes(var)
  File "/home/efes/.cache/pypoetry/virtualenvs/meta-world-v48m9Vhg-py3.10/lib/python3.10/site-packages/xarray/backends/h5netcdf_.py", line 65, in _read_attributes
    for k, v in h5netcdf_var.attrs.items():
  File "/usr/lib/python3.10/_collections_abc.py", line 906, in __iter__
    yield (key, self._mapping[key])
  File "/home/efes/.cache/pypoetry/virtualenvs/meta-world-v48m9Vhg-py3.10/lib/python3.10/site-packages/h5netcdf/attrs.py", line 72, in __getitem__
    if not np.isscalar(output) and len(output) == 1:
TypeError: object of type 'h5py.h5r.Reference' has no len()
```

**Comment by kmuehlbauer** [comment]
Thanks @fsvenson, that's helpful. So if you just want to get back the reference we could do this as suggested. I've no idea about the implications this might have downstream. What does netcdf4 engine return in this situation?

**Comment by kmuehlbauer** [comment]
I looks like netcdf4-python is just ignoring attributes with type reference. 

In the past `h5netcdf` added these features which are unsupported in netcdf4/netcdf-c as `invalid_netcdf`. 

Looking at https://github.com/h5netcdf/h5netcdf/blob/18c86f414cc2915a78cc5f30c25ab5f65bae2139/h5netcdf/core.py#L1127-L1148 `dtype="reference"` is already checked. So we can already write references with kwarg `invalid_netcdf=True`. This is most likely a regression which need to be taken care of in `__getitem__` as you already suggested.

We need to check if that collides with the HIDDEN attributes somehow.

**Comment by kmuehlbauer** [comment]
@fsvenson Sorry, this fell through the cracks. Are you still in the works with this? Would you be able to create a MCVE producing such file (eg via h5py) or provide a small file to play with? Thanks!
